### ISSUE TITLE
Long tap and release on devices gives session lost popup all the time

### ISSUE THREAD

**Issue by Gnanaprakash22** [shamanec/GADS#129]
<img width="539" alt="Screenshot 2024-11-10 at 12 41 47 PM" src="https://github.com/user-attachments/assets/3f5efe09-997d-415a-9315-0bf9f83eb725">

**Comment by shamanec** [comment]
Which OS is that? Also is it in landscape?

**Comment by Gnanaprakash22** [comment]
i m seeing this in 17.5.1 and 15.8.3 , it is happening in portrait/landscape

**Comment by shamanec** [comment]
This particular snippet shows the session timed out after 120 seconds? If you go back and reopen the device does it start working again? Also are you using the custom WDA from my fork?

**Comment by Gnanaprakash22** [comment]
yes it works fine after capturing the device again , i'm using custom wda only from your forked branch. Is the issue reproducible from your side?

**Comment by shamanec** [comment]
I haven't tested yet but I have an assumption why it happens - with mainstream WDA the interactions go through Appium so the session refreshes each time you do something. With my WDA the interaction endpoints do not use a session so even if you tap/swipe for Appium its like nothing has been done and at some point the session expires... I didn't really think about that so it is something I need to fix in some way :( 😅

**Comment by shamanec** [comment]
If you are building the provider from source instead of using the prebuilt binaries you can go [here](https://github.com/shamanec/GADS/blob/068613fe8c0bc55f8c575aae3e196d0a25dc3a68/provider/devices/health.go#L73) and [here](https://github.com/shamanec/GADS/blob/068613fe8c0bc55f8c575aae3e196d0a25dc3a68/provider/devices/health.go#L81) and update the value to something bigger - this should help until I have the time and find a reasonable way to handle this

**Comment by shamanec** [comment]
@Gnanaprakash22 I've updated the session management implementation in the latest release - default device control Appium session timeout is 30 minutes, so if for some reason it expires I've added a button to refresh it directly from the device control UI. Also I've implemented a separate "control" session that is also 30 minutes, so if someone is controlling the device and does not perform any action for 30 minutes they will be kicked out and the device released

**Comment by Gnanaprakash22** [comment]
@shamanec thanks for the update

**Comment by Gnanaprakash22** [comment]
@shamanec long tap and hold is giving 

<img width="553" alt="Screenshot 2024-12-03 at 3 16 02 PM" src="https://github.com/user-attachments/assets/19a02eb7-4ad7-41da-8522-a61a545aa721">

**Comment by shamanec** [comment]
@Gnanaprakash22 does this happen consistently? is it possible that the session has just expired? What if you reload the Appium session from the button above the canvas, does it still show an error after? When it happens does it happen only for touch&hold?

**Comment by Gnanaprakash22** [comment]
i see it happens only for touch and hold @shamanec

**Comment by shamanec** [comment]
@Gnanaprakash22 sorry for the delay? is this in both landscape and portrait? is it using custom WDA from my fork or mainstream WDA? I can't seem to reproduce it right now

**Comment by Gnanaprakash22** [comment]
@shamanec sorry for the delay in response i m using version 2.4.1 and I'm still facing issues
let me update the version and check

**Comment by Gnanaprakash22** [comment]
@shamanec i m still facing the same issue and also i m not able to input any text using textfield any recommended appium & xcuitest driver version ?

<img width="519" alt="Screenshot 2024-12-20 at 8 54 42 PM" src="https://github.com/user-attachments/assets/86aa3342-2a43-454e-8d9d-dcde79dc8197" />

**Comment by Gnanaprakash22** [comment]
typeText api is giving 500 internal server error with "invalid character '\'' looking for beginning of object key string" response

**Comment by Gnanaprakash22** [comment]
@shamanec FYI I'm facing this Touch and hold issue & Text input in ios devices , haven't verified the same in android so please check this from your end if possible in ios devices

**Comment by Gnanaprakash22** [comment]
@shamanec did you get a chance to check Touch and hold & Text input issues in ios devices ?

**Comment by shamanec** [comment]
@Gnanaprakash22 hey, man, not yet, sorry about that, I was quite busy and now its Christmas holiday 😅 Just to make sure, you are trying to type in English? Because this uses Appium under the hood and I believe it does not support any other language

**Comment by shamanec** [comment]
@Gnanaprakash22 nvm, I found the issue with typing, I've create a hotfix release 2.6.1. I will look into the touch&hold issue next :P

**Comment by Gnanaprakash22** [comment]
@shamanec 
Thank you for the quick release! 😊 Just to clarify, I’m entering text in English only, no other languages. Apologies for reaching out during the holidays—there’s no rush at all. Enjoy your holidays and have a Merry Christmas! 🎄✨

**Comment by shamanec** [comment]
@Gnanaprakash22 it should work now, I released 2.6.2 hotfix. There was an issue both in portrait for touch&hold and in landscape for all actions with custom WDA, stupid mistake on my part 😅

**Comment by Gnanaprakash22** [comment]
@shamanec Awesome, thanks for the update !!!

**Comment by shamanec** [comment]
You got it, feel free to close the issue if everything is fine 🙃

**Comment by Gnanaprakash22** [comment]
sure will do it

**Comment by Gnanaprakash22** [comment]
@shamanec touch and hold issue persists, The uninstall app option is not working
attaching video for those issues 
[](https://drive.google.com/file/d/1BTuVncZTPqr-vAMZOPRbVWqVOvekr7E-/view?usp=sharing)

uninstallApp api call returns {"error":"Invalid payload"} 400 bad request

**Comment by shamanec** [comment]
I'll check the uninstall issue but I am really at odds for the touch&hold issue, it works for all my device in both portrait&landscape... Are you sure it doesnt send any request to the server when you attempt it? 😢

**Comment by Gnanaprakash22** [comment]
yes, I am not getting network calls, only for tap I'm getting and not for press & hold
also can you please share a video on how to use Get clipboard option

**Comment by shamanec** [comment]
I saw the problem with uninstall, will release a hotfix tomorrow and share a video on clipboard. I am not sure what to do with touch&hold though, its doesnt seem possible to show an error without sending a request.. you are checking in the browser, right? Is there something printed in the browser console? Also are you using a prebuilt binary from releases or you build from source?

**Comment by Gnanaprakash22** [comment]
I am building from the source, in the console i see this for touch & hold

Failed to load resource: the server responded with a status of 404 (Not Found)

for this endpoint device/<deviceId>/touchAndHold getting 

{
  "error": "unauthorized"
}

**Comment by shamanec** [comment]
Does it have an actual device id or its empty?can you for the sake of the test try running a prebuilt binary from the latest release instead of building from source? :)

**Comment by shamanec** [comment]
App uninstall fix is on PR, I'll release it later today. Here is a video of get clipboard (you just copy whatever and press the button)

https://github.com/user-attachments/assets/d1061f5d-30de-475e-a09a-599c9e109539

**Comment by Gnanaprakash22** [comment]
Thanks for the video !!! , device id is displayed in touch&hold api call , will try running prebuilt binary too . Do I have to update Webdriveragent too 
https://github.com/shamanec/WebDriverAgent
?

**Comment by shamanec** [comment]
I havent done any changes soon but you could try updating just in case 🥲

**Comment by Gnanaprakash22** [comment]
my suspicion was right , updating the webdriver agent fixed touch and hold issue but i see the screen is blank when taking control of device , we have to click multiple times to get the screen visible

https://drive.google.com/file/d/1pjmsvu4A2kfcl5uaqRl0l_Rh19HEmVzm/view?usp=sharing

Logs

INFO[1070] new client connected                          conn="&forward.ConnListener{listener:(*net.TCPListener)(0xc000c86000), quit:(chan interface {})(0xc0000ba2a0)}"
INFO[1070] Connected to port                             conn="&net.TCPConn{conn:net.conn{fd:(*net.netFD)(0xc000dd4080)}}" phonePort=9100
INFO[1070] outputReceived:fromProcess:atTime:            fields.msg="2025-01-10 19:25:59.233953+0530 WebDriverAgentRunner-Runner[43332:6707618] Got screenshots broadcast client connection at 127.0.0.1:65166\n" fields.time=52544524937718 pid=43332
INFO[1070] outputReceived:fromProcess:atTime:            fields.msg="2025-01-10 19:25:59.235023+0530 WebDriverAgentRunner-Runner[43332:6707618] Starting screenshots broadcast for the client at 127.0.0.1:65166\n" fields.time=52544524960752 pid=43332
ERRO[1092] forward: close clientConn --> deviceConn     
ERRO[1092] forward: close clientConn <-- deviceConn

**Comment by shamanec** [comment]
Yeah, this is not a bug but an "optimization" 🤣 I changed the screenshot broadcast in the custom WebDriverAgent to skip sending frames when nothing changes on the screen to save bandwidth. I will see if I can make it send one initial frame because I agree its annoying, Let's close this thread because it became too big for multiple different things and you can open a new issue for next problems :)

**Comment by Gnanaprakash22** [comment]
sure sure i will close it and report this webdriveragent issue as a new one , thanks for fixing other issues apart from mentioned ones  🤣
